language: python
python:
  - "2.7"

cache:
  directories:
    - $HOME/.cache/pip

before_install:
  - redis-server redis.conf &

install:
  - python setup.py install

script:
  - coverage run `which nosetests` -c nose.cfg -c $KB_NOSE_CFG
  - coverage report

env:
  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-local.cfg
  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-local.cfg
#  - KB_REDIS_HOST=localhost; KB_NOSE_CFG=nose-ci.cfg
#  - KB_REDIS_HOST="";        KB_NOSE_CFG=nose-ci.cfg

after_success:
  - codecov
