language: python
python:
  - "2.7"

git:
  submodules: false

before_install:
  - git submodule update --init --recursive

install:
  - mv requirements.txt requirements.txt-
  - cp requirements-travis.txt requirements.txt
  - python setup.py install

script:
  - cd lib
  - touch .coverage
  - cd ..
  - coverage run --source=doekbase.data_api /home/travis/virtualenv/python2.7.9/bin/nosetests --with-timer --ws-url=test_resources/data --wsfile-msgpack
  - coverage report

after_success:
  - codecov
